export const CONFIG_CATEGORIES = [
  { category: 'base', title: '基础配置', description: '股票列表和任务行为' },
  { category: 'analysis', title: '分析策略', description: '技术指标与买卖纪律阈值' },
  { category: 'agent', title: '问股 Agent', description: '策略问答与多轮会话' },
  { category: 'notification', title: '通知配置', description: '推送渠道与报告样式' },
  { category: 'system', title: '系统设置', description: '认证与运行时参数' },
];

export const DEFAULT_SYSTEM_CONFIGS = [
  {
    key: 'STOCK_LIST',
    value: '600519,000001,00700,AAPL,TSLA',
    category: 'base',
    title: '默认股票池',
    description: '分析任务默认的股票代码列表，逗号分隔',
  },
  {
    key: 'ANALYSIS_CONCURRENCY',
    value: '2',
    category: 'base',
    title: '分析并发数',
    description: '单次批量分析的并发任务数量',
  },
  {
    key: 'BIAS_THRESHOLD',
    value: '5',
    category: 'analysis',
    title: '乖离率阈值(%)',
    description: '高于阈值提示追高风险',
  },
  {
    key: 'NEWS_MAX_AGE_DAYS',
    value: '3',
    category: 'analysis',
    title: '新闻时效(天)',
    description: '新闻超出时效后不计入分析依据',
  },
  {
    key: 'NEWS_SYNC_ENABLED',
    value: 'true',
    category: 'system',
    title: '资讯定时同步开关',
    description: '是否启用焦点资讯定时同步任务',
  },
  {
    key: 'NEWS_SYNC_TICK_SECONDS',
    value: '60',
    category: 'system',
    title: '资讯调度检查周期(秒)',
    description: '定时调度器轮询间隔，建议 30~300 秒',
  },
  {
    key: 'NEWS_SYNC_RETRY_MAX',
    value: '3',
    category: 'system',
    title: '资讯同步最大重试次数',
    description: '同一分类连续失败时的重试次数上限',
  },
  {
    key: 'NEWS_SYNC_RETRY_BASE_SECONDS',
    value: '60',
    category: 'system',
    title: '资讯重试基础间隔(秒)',
    description: '重试采用指数退避，基础间隔会按 2^n 增长',
  },
  {
    key: 'NEWS_SYNC_CATALOG_REFRESH_MINUTES',
    value: '360',
    category: 'system',
    title: '资讯目录刷新间隔(分钟)',
    description: '调度器定时刷新 provider 分类目录的间隔',
  },
  {
    key: 'NEWS_SYNC_LOOKBACK_MINUTES',
    value: '180',
    category: 'system',
    title: '资讯增量回看窗口(分钟)',
    description: '增量同步回看窗口，避免漏采',
  },
  {
    key: 'NEWS_SCHEDULER_CONCURRENCY',
    value: '1',
    category: 'system',
    title: '资讯调度并发数',
    description: '单次调度 tick 并发处理的分类数量',
  },
  {
    key: 'NEWS_BOOTSTRAP_DAYS',
    value: '7',
    category: 'system',
    title: '资讯启动补齐天数',
    description: '服务启动后自动补齐最近 N 天资讯',
  },
  {
    key: 'NEWS_AI_DIGEST_ENABLED',
    value: 'false',
    category: 'system',
    title: '资讯AI摘要开关',
    description: '是否启用焦点资讯摘要任务',
  },
  {
    key: 'NEWS_AI_DIGEST_SCHEDULE',
    value: '09:30,12:30,15:30,20:30',
    category: 'system',
    title: '资讯AI摘要时点',
    description: '每日触发摘要生成的本地时间点，逗号分隔',
  },
  {
    key: 'NEWS_MAX_ITEMS_PER_RUN',
    value: '1000',
    category: 'system',
    title: '单次资讯采集上限',
    description: '每次采集最多处理条数，防止长尾阻塞',
  },
  {
    key: 'NEWS_PROVIDER_TUSHARE_ENABLED',
    value: 'true',
    category: 'system',
    title: 'Tushare资讯源开关',
    description: '是否启用 Tushare 作为资讯 provider',
  },
  {
    key: 'TUSHARE_WEB_COOKIE',
    value: '',
    category: 'system',
    title: 'Tushare网页Cookie',
    description: '用于 news 页面抓取兜底的登录态 Cookie，优先于环境变量读取',
  },
  {
    key: 'NEWS_PROVIDER_XUEQIU_ENABLED',
    value: 'true',
    category: 'system',
    title: '雪球资讯源开关',
    description: '是否启用 雪球7x24 作为资讯 provider',
  },
  {
    key: 'AGENT_MODE',
    value: 'true',
    category: 'agent',
    title: '启用问股 Agent',
    description: '开启策略问答能力',
  },
  {
    key: 'AGENT_SKILLS',
    value: 'ma_golden_cross,chan_theory,wave_theory,volume_breakout',
    category: 'agent',
    title: '默认启用策略',
    description: '逗号分隔，定义问股策略列表',
  },
  {
    key: 'REPORT_TYPE',
    value: 'full',
    category: 'notification',
    title: '报告类型',
    description: 'simple/full/brief',
  },
  {
    key: 'SINGLE_STOCK_NOTIFY',
    value: 'false',
    category: 'notification',
    title: '单股即时推送',
    description: '每分析完一只股票立即推送',
  },
  {
    key: 'EMAIL_ENABLED',
    value: 'false',
    category: 'notification',
    title: '启用邮件通知',
    description: '分析完成后发送邮件通知',
  },
  {
    key: 'EMAIL_SMTP_HOST',
    value: '',
    category: 'notification',
    title: 'SMTP Host',
    description: '邮件服务器地址，如 smtp.qq.com',
  },
  {
    key: 'EMAIL_SMTP_PORT',
    value: '465',
    category: 'notification',
    title: 'SMTP Port',
    description: '邮件服务器端口，常见 465/587',
  },
  {
    key: 'EMAIL_SMTP_SECURE',
    value: 'true',
    category: 'notification',
    title: 'SMTP Secure',
    description: '是否启用 SSL/TLS',
  },
  {
    key: 'EMAIL_SENDER',
    value: '',
    category: 'notification',
    title: '发件邮箱',
    description: '例如 yourname@example.com',
  },
  {
    key: 'EMAIL_PASSWORD',
    value: '',
    category: 'notification',
    title: '邮箱密码/授权码',
    description: '建议使用邮箱授权码',
  },
  {
    key: 'EMAIL_RECEIVERS',
    value: '',
    category: 'notification',
    title: '收件邮箱',
    description: '多个收件人用逗号分隔',
  },
  {
    key: 'TRADING_DAY_CHECK_ENABLED',
    value: 'true',
    category: 'system',
    title: '交易日检查',
    description: '非交易日自动跳过任务',
  },
  {
    key: 'AUTH_ENABLED',
    value: 'false',
    category: 'system',
    title: '启用登录认证',
    description: 'Web 管理界面与 API 认证开关',
  },
];

export const AGENT_MODELS = [
  { id: 'heuristic-v1', name: 'Heuristic Analyst v1', provider: 'local', supportsStream: true },
  { id: 'trend-scout-v1', name: 'Trend Scout v1', provider: 'local', supportsStream: false },
];

export const STRATEGY_LIBRARY = [
  { key: 'ma_golden_cross', name: '均线金叉策略', description: '识别 MA5 上穿 MA10 的趋势启动点' },
  { key: 'chan_theory', name: '缠论结构策略', description: '识别中枢与背驰信号，偏中期节奏' },
  { key: 'wave_theory', name: '波浪结构策略', description: '识别推动浪与调整浪，给出节奏建议' },
  { key: 'volume_breakout', name: '放量突破策略', description: '放量突破箱体上沿后的跟随交易' },
  { key: 'box_oscillation', name: '箱体震荡策略', description: '高抛低吸，适配横盘市场' },
  { key: 'shrink_pullback', name: '缩量回踩策略', description: '回踩 MA5/MA10 且缩量时寻找低吸点' },
  { key: 'dragon_head', name: '龙头接力策略', description: '强势板块龙头延续性跟踪' },
  { key: 'emotion_cycle', name: '情绪周期策略', description: '结合连板高度和情绪拐点' },
  { key: 'bull_trend', name: '多头趋势策略', description: 'MA5 > MA10 > MA20 趋势跟踪' },
  { key: 'bottom_volume', name: '底部放量策略', description: '低位放量确认资金回流' },
  { key: 'one_yang_three_yin', name: '一阳三阴策略', description: '强弱切换的短线形态识别' },
];
